try:
    # Code qui pourrait générer une exception
    resultat = 10 / 0  # Division par zéro pour illustrer l'exception
except ZeroDivisionError:
    # Code de gestion de l'exception
    print("Erreur : Division par zéro")
